export const GET_WEEKLY = "GET_WEEKLY"
export const GET_BOOK = "GET_BOOK"
export const SEARCH_BOOK = "SEARCH_BOOK"
export const GET_BOOKS_LIST = "GET_BOOKS_LIST"
export const ADD_BOOK = "ADD_BOOK"
export const GET_RECOMMEND = "GET_RECOMMEND"

export const GET_BOOK_REVIEWS = "GET_BOOK_REVIEWS"
export const GET_SPECIFIC_REVIEW = "GET_SPECIFIC_REVIEW"
export const UPDATE_SPECIFIC_REVIEW = "UPDATE_SPECIFIC_REVIEW"

export const GET_USER = "GET_USER"
export const UPDATE_USER = "UPDATE_USER"

export const GET_LOGS = "GET_LOGS"
export const ADD_LOG = "ADD_LOGS"

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_ERROR = "USER_AUTH_ERROR"
